from mymodules.builder import Builder
from mymodules.action.install_remove import StartKickingSomeNinjas

class InitConnectMeSignals(object):
    def __init__(self):
        ninja = StartKickingSomeNinjas
        Builder.builder.connect_signals(self)

        # connect "clicked" signal to those Menu7 buttons
        Menu7.geany_.connect("clicked", ninja, 'geany')
        Menu7.blender_.connect("clicked", ninja, 'blender')
        Menu7.ninja_ide_.connect("clicked", ninja, 'ninja-ide')
        Menu7.glade_.connect("clicked", ninja, 'glade')
        Menu7.audacious_.connect("clicked", ninja, 'audacious')
        Menu7.gimp_.connect("clicked", ninja, 'gimp')
        Menu7.evince_.connect("clicked", ninja, 'evince')
        Menu7.xfburn_.connect("clicked", ninja, 'xfburn')
        Menu7.flashplayer_.connect("clicked", ninja, 'flashplugin')
        Menu7.openshot_.connect("clicked", ninja, 'openshot')
        Menu7.chromium_.connect("clicked", ninja, 'chromium')
        Menu7.deluge_.connect("clicked", ninja, 'deluge')
        Menu7.liferea_.connect("clicked", ninja, 'liferea')
        Menu7.htop_.connect("clicked", ninja, 'htop')
        Menu7.skype_.connect("clicked", ninja, 'skype')
        Menu7.wireshark_.connect("clicked", ninja, 'wireshark')
        Menu7.virtualbox_.connect("clicked", ninja, 'virtualbox')
        Menu7.steam_.connect("clicked", ninja, 'steam')
        Menu7.xchat_.connect("clicked", ninja, 'xchat')
        Menu7.gedit_.connect("clicked", ninja, 'gedit')

class Menu7(object):
    # get menu 7 application buttons
    geany_ = Builder.builder8.get_object("geany_")
    blender_ = Builder.builder8.get_object("blender_")
    ninja_ide_ = Builder.builder8.get_object("ninja_ide_")
    glade_ = Builder.builder8.get_object("glade_")
    audacious_ = Builder.builder8.get_object("audacious_")
    gimp_ = Builder.builder8.get_object("gimp_")
    evince_ = Builder.builder8.get_object("evince_")
    xfburn_ = Builder.builder8.get_object("xfburn_")
    flashplayer_ = Builder.builder8.get_object("flashplayer_")
    openshot_ = Builder.builder8.get_object("openshot_")
    chromium_ = Builder.builder8.get_object("chromium_")
    deluge_ = Builder.builder8.get_object("deluge_")
    liferea_ = Builder.builder8.get_object("liferea_")
    htop_ = Builder.builder8.get_object("htop_")
    skype_ = Builder.builder8.get_object("skype_")
    wireshark_ = Builder.builder8.get_object("wireshark_")
    virtualbox_ = Builder.builder8.get_object("virtualbox_")
    steam_ = Builder.builder8.get_object("steam_")
    xchat_ = Builder.builder8.get_object("xchat_")
    gedit_ = Builder.builder8.get_object("gedit_")
    # add tooltip for each application icon
    geany_icon_tooltip_ = Builder.builder8.get_object("geany_icon_tooltip_")
    geany_icon_tooltip_.set_tooltip_text("Geany is a small and lightweight integrated development environment.")
    blender_icon_tooltip_ = Builder.builder8.get_object("blender_icon_tooltip_")
    blender_icon_tooltip_.set_tooltip_text("Blender is the open source, cross platform suite of tools for 3D creation.")
    ninja_ide_icon_tooltip_ = Builder.builder8.get_object("ninja_ide_icon_tooltip_")
    ninja_ide_icon_tooltip_.set_tooltip_text("Ninja-IDE is a cross-platform integrated development environment designed to build Python applications.")
    glade_icon_tooltip_ = Builder.builder8.get_object("glade_icon_tooltip_")
    glade_icon_tooltip_.set_tooltip_text("Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.")
    audacious_icon_tooltip_ = Builder.builder8.get_object("audacious_icon_tooltip_")
    audacious_icon_tooltip_.set_tooltip_text("Audio player with support for many formats, and it has support for third-party plugins.")
    gimp_icon_tooltip_ = Builder.builder8.get_object("gimp_icon_tooltip_")
    gimp_icon_tooltip_.set_tooltip_text("GIMP is an image retouching and editing tool, similar to Photoshop.")
    evince_icon_tooltip_ = Builder.builder8.get_object("evince_icon_tooltip_")
    evince_icon_tooltip_.set_tooltip_text("Evince is a document viewer for multiple document formats.")
    xfburn_icon_tooltip_ = Builder.builder8.get_object("xfburn_icon_tooltip_")
    xfburn_icon_tooltip_.set_tooltip_text("Xfburn is a simple CD/DVD burning tool")
    flashplayer_icon_tooltip_ = Builder.builder8.get_object("flashplayer_icon_tooltip_")
    flashplayer_icon_tooltip_.set_tooltip_text("Cross-platform plugin plays animations, videos and sound files.")
    openshot_icon_tooltip_ = Builder.builder8.get_object("openshot_icon_tooltip_")
    openshot_icon_tooltip_.set_tooltip_text("A simple, powerful, and free open-source video editor for Linux with a focus on usability, flexibility, and style")
    chromium_icon_tooltip_ = Builder.builder8.get_object("chromium_icon_tooltip_")
    chromium_icon_tooltip_.set_tooltip_text("Chromium is the open source web browser project from which Google Chrome draws its source code.")
    deluge_icon_tooltip_ = Builder.builder8.get_object("deluge_icon_tooltip_")
    deluge_icon_tooltip_.set_tooltip_text("Open source, cross-platform BitTorrent client.")
    liferea_icon_tooltip_ = Builder.builder8.get_object("liferea_icon_tooltip_")
    liferea_icon_tooltip_.set_tooltip_text("Liferea is an abbreviation for Linux Feed Reader, a news aggregator for online news feeds.")
    htop_icon_tooltip_ = Builder.builder8.get_object("htop_icon_tooltip_")
    htop_icon_tooltip_.set_tooltip_text("Htop is an interactive system-monitor process-viewer.")
    skype_icon_tooltip_ = Builder.builder8.get_object("skype_icon_tooltip_")
    skype_icon_tooltip_.set_tooltip_text("Skype is a freemium voice-over-IP service and instant messaging client")
    wireshark_icon_tooltip_ = Builder.builder8.get_object("wireshark_icon_tooltip_")
    wireshark_icon_tooltip_.set_tooltip_text("Wireshark is a free and open-source packet analyzer. It is used for network troubleshooting, analysis,\nsoftware and communications protocol development.")
    virtualbox_icon_tooltip_ = Builder.builder8.get_object("virtualbox_icon_tooltip_")
    virtualbox_icon_tooltip_.set_tooltip_text("VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use.\nThe program is similar to Virtual PC.")
    steam_icon_tooltip_ = Builder.builder8.get_object("steam_icon_tooltip_")
    steam_icon_tooltip_.set_tooltip_text("Steam is a digital distribution, digital rights management, multiplayer, and communications platform developed by\nValve Corporation. It is used to distribute games and related media online, from small independent developers to larger software houses.")
    xchat_icon_tooltip_ = Builder.builder8.get_object("xchat_icon_tooltip_")
    xchat_icon_tooltip_.set_tooltip_text("XChat is a popular Internet Relay Chat (IRC) client.")
    gedit_icon_tooltip_ = Builder.builder8.get_object("gedit_icon_tooltip_")
    gedit_icon_tooltip_.set_tooltip_text("Gedit is lightweight text editor.")

    @staticmethod
    def load_icons_n_tooltips_at_startup():
        from mymodules.categories.somesome import menu7
        menu7.load()